-- Solution-1: Using INNER JOIN

SELECT CITY.NAME FROM CITY INNER JOIN COUNTRY ON COUNTRYCODE = CODE WHERE CONTINENT = 'Africa';


-- Solution-2: Without INNER JOIN

SELECT NAME FROM CITY WHERE COUNTRYCODE IN( 
 SELECT CODE FROM COUNTRY WHERE CONTINENT = 'Africa'
);