-- Solution-1: Using CASE

SELECT N, (
  CASE
    WHEN P IS NULL THEN 'Root'
    WHEN N IN(SELECT N FROM BST WHERE N IN (SELECT P FROM BST)) THEN 'Inner'
    ELSE 'Leaf'
  END
)FROM BST ORDER BY N;
   

-- Solution-2: Using IF()

SELECT N, (
  IF(P IS NULL, 'Root',
  IF(N IN(SELECT N FROM BST WHERE N IN (SELECT P FROM BST)), 'Inner', 'Leaf'))
)FROM BST ORDER BY N;
   

-- Solution-3: Using LEFT JOIN

SELECT DISTINCT(BST1.N),
CASE
  WHEN BST1.P IS NULL THEN 'Root'
  WHEN BST2.P IS NULL THEN 'Leaf'
  ELSE 'Inner'
END
FROM BST BST1 LEFT JOIN BST BST2 ON BST1.N = BST2.P ORDER BY BST1.N;
   
