-- Solution-1: Without using joins

SELECT COMPANY_CODE, 
(SELECT FOUNDER FROM COMPANY WHERE COMPANY.COMPANY_CODE = EMPLOYEE.COMPANY_CODE),
COUNT(DISTINCT(LEAD_MANAGER_CODE)),
COUNT(DISTINCT(SENIOR_MANAGER_CODE)),
COUNT(DISTINCT(MANAGER_CODE)),
COUNT(DISTINCT(EMPLOYEE_CODE))
FROM EMPLOYEE GROUP BY COMPANY_CODE ORDER BY COMPANY_CODE;


-- Solution-2: Using NATURAL JOIN

SELECT COMPANY_CODE, 
FOUNDER, 
COUNT(DISTINCT(LEAD_MANAGER_CODE)), 
COUNT(DISTINCT(SENIOR_MANAGER_CODE)), 
COUNT(DISTINCT(MANAGER_CODE)), 
COUNT(DISTINCT(EMPLOYEE_CODE)) 
FROM EMPLOYEE NATURAL JOIN COMPANY GROUP BY COMPANY_CODE, FOUNDER ORDER BY COMPANY_CODE;