/*
Enter your query here.
*/

-- TLDR: Find cheapest wand for given combination of age and power
-- (or code and power since age and code are one-one)

SELECT ID, AGE, COINS_NEEDED, POWER
FROM WANDS, WANDS_PROPERTY
WHERE WANDS.CODE = WANDS_PROPERTY.CODE
AND IS_EVIL = 0
AND (COINS_NEEDED, WANDS.CODE, POWER) IN 
(SELECT MIN(COINS_NEEDED), WANDS.CODE, POWER
FROM WANDS, WANDS_PROPERTY
WHERE WANDS.CODE = WANDS_PROPERTY.CODE
GROUP BY WANDS.CODE, POWER)
ORDER BY POWER DESC,
AGE DESC;


-- In the previous solution, sub-query runs for every row in the result set.
-- If done like this instead, the sub-query is run once, when performing the join:

SELECT ID, MIN_PRICES.AGE, COINS_NEEDED, WANDS.POWER
FROM WANDS,(
 SELECT WANDS.CODE, POWER, MIN(WANDS_PROPERTY.AGE) AS AGE, MIN(WANDS.COINS_NEEDED) AS MIN_PRICE
 FROM WANDS, WANDS_PROPERTY
 WHERE WANDS.CODE = WANDS_PROPERTY.CODE
 AND WANDS_PROPERTY.IS_EVIL = 0
 GROUP BY WANDS.CODE, POWER   
) AS MIN_PRICES
WHERE WANDS.CODE = MIN_PRICES.CODE
AND WANDS.POWER = MIN_PRICES.POWER
AND WANDS.COINS_NEEDED = MIN_PRICES.MIN_PRICE
ORDER BY WANDS.POWER DESC, MIN_PRICES.AGE DESC;