-- Solution-1: Using IF + INNER JOIN

SELECT IF(GRADE>=8, NAME, NULL), GRADE, MARKS
FROM STUDENTS INNER JOIN GRADES
ON MARKS BETWEEN MIN_MARK AND MAX_MARK
ORDER BY GRADE DESC, IF(GRADE>=8, NAME, MARKS) ASC;


-- Solution-2: Using IF, CASE + INNER JOIN

SELECT IF(GRADE>=8, NAME, NULL), GRADE, MARKS
FROM STUDENTS INNER JOIN GRADES
ON MARKS BETWEEN MIN_MARK AND MAX_MARK
ORDER BY GRADE DESC,
(CASE 
  WHEN GRADE>=8 
  THEN NAME
  ELSE MARKS
END) ASC;