-- Join 4 tables to obtain required result

/*
Enter your query here.
*/

SELECT HACKERS.HACKER_ID, HACKERS.NAME FROM HACKERS, SUBMISSIONS, CHALLENGES, DIFFICULTY 
WHERE HACKERS.HACKER_ID = SUBMISSIONS.HACKER_ID
AND SUBMISSIONS.CHALLENGE_ID = CHALLENGES.CHALLENGE_ID
AND CHALLENGES.DIFFICULTY_LEVEL = DIFFICULTY.DIFFICULTY_LEVEL
AND SUBMISSIONS.SCORE = DIFFICULTY.SCORE
GROUP BY HACKERS.HACKER_ID, HACKERS.NAME
HAVING COUNT(CHALLENGES.CHALLENGE_ID)>1
ORDER BY 
COUNT(CHALLENGES.CHALLENGE_ID) DESC,
HACKERS.HACKER_ID ASC;
    