-- Solution-1: Without sorting

SELECT MAX(SALARY*MONTHS), COUNT(SALARY*MONTHS) FROM EMPLOYEE WHERE SALARY*MONTHS = (SELECT MAX(SALARY*MONTHS) FROM EMPLOYEE);


-- Solution-2: Using sorting

SELECT SALARY*MONTHS AS EARNINGS, COUNT(SALARY*MONTHS) FROM EMPLOYEE
GROUP BY EARNINGS
ORDER BY EARNINGS DESC
LIMIT 1;