-- Solution-1: Without sorting

SELECT ROUND(LONG_W, 4) FROM STATION 
WHERE 
LAT_N = (SELECT MAX(LAT_N) FROM STATION WHERE LAT_N<137.2345);


-- Solution-2: Sort by LAT_N

SELECT ROUND(LONG_W, 4) FROM STATION 
WHERE LAT_N<137.2345
ORDER BY LAT_N DESC LIMIT 1;