-- Solution - 1 : Use DISTINCT, % operator

SELECT DISTINCT(CITY) FROM STATION WHERE ID%2 = 0;

-- Solution - 2 : Use DISTINCT, MOD

SELECT DISTINCT(CITY) FROM STATION WHERE MOD(ID,2) = 0;

-- Solution - 3 : Use GROUP BY instead of DISTINCT

SELECT CITY FROM STATION WHERE MOD(ID,2) = 0 GROUP BY CITY;